### ISSUE TITLE
Reorganise /app folder - make sure all folders inside of src are themselves modules

### ISSUE THREAD

**Issue by cjteam123** [cse403trackforever/webapp#126]
"I think it would be a good idea to clean up the organization of trackforever/webapp/src/app/. It's good for the most part, but the files at that level should be moved into folders."

**Comment by djdupre** [comment]
Each top-level folder should be a module. See https://angular.io/guide/styleguide#overall-structural-guidelines

**Comment by cjteam123** [comment]
Wanna set this as wontfix?

**Comment by djdupre** [comment]
No. Our top-level folders _aren't_ modules and they should be.

**Comment by cjteam123** [comment]
Ah gotcha!

**Comment by cjteam123** [comment]
Out of scope!
