### ISSUE TITLE
Sign-out button doesn't actually sign a user out

### ISSUE THREAD

**Issue by cjteam123** [cse403trackforever/webapp#136]
Easy to replicate on the public website 
https://cse403trackforever.firebaseapp.com
Just sign in, sign out, and the issue will occur.

**Comment by christineta** [comment]
@cjteam123 I can't seem to replicate this. What do you mean doesn't actually sign out?

After signing out, I'm redirected to the homepage. Accessing /myprojects isn't allowed (Although the user settings page is and I'll take a look at that)

**Comment by cjteam123** [comment]
Looks like it was an issue on my end. Clearing the cached data and the local DB fixed the issue.
