### ISSUE TITLE
Fix various Google Code conversion problems

### ISSUE THREAD

**Issue by djdupre** [cse403trackforever/webapp#159]
A few problems came up during evaluation:
- The submit time is missing. The first comment of a Google Code issue is that issue's report, so the timestamp from the first comment can be used as the submit time
- Commenters should not be labeled "0, 1, 2, 3" etc. but should instead have consistent IDs
- Empty comments should preserve the "(No comment was entered for this change.)" note or be removed
- Some comments *do* need markdown, so maybe #103 was wrong

**Comment by WilliamCao13** [comment]
Additional problems:
* The very first issue of [this project](https://code.google.com/archive/p/openbookproject/) never imported.
* Line breaks are not showing up for all issues in [this project](https://code.google.com/archive/p/openbookproject/). I believe this always occurs every time a ```<p>``` tag is used.
  - Here's [an example issue](https://code.google.com/archive/p/openbookproject/issues/96) that can be used as reference to how it should look like
* ```<hr>``` tags not showing up correctly
  - Refer to [this example](https://code.google.com/archive/p/openbookproject/issues/130) in the same project.
* Empty comments. Refer to [this issue](https://code.google.com/archive/p/openbookproject/issues/359) with a single empty comment or [this one](https://code.google.com/archive/p/openbookproject/issues/725) which has multiple empty comments.
* Different number of asterisks are showing up in issues similar to [this one](https://code.google.com/archive/p/openbookproject/issues/763)
* Markdown issues, specifically with headings and ```<em>``` tags shown by [this issue](https://code.google.com/archive/p/openbookproject/issues/824) and [this one](https://code.google.com/archive/p/openbookproject/issues/1041)
* Underscores appearing when they shouldn't be [(reference).](https://code.google.com/archive/p/openbookproject/issues/827) There is a ```<strong>``` tag in the browser when viewing the last comment, specifically around the word ```init```.
  - There are no errors regarding the ```<b>``` tag though.
