### ISSUE TITLE
Add documentation and comments

### ISSUE THREAD

**Issue by christineta** [cse403trackforever/webapp#201]

**Comment by djdupre** [comment]
@cjteam123 Can you document the hash and prevHash fields? I started here:
https://github.com/cse403trackforever/webapp/blob/docs/src/app/import/models/trackforever/trackforever-project.ts#L14

**Comment by cjteam123** [comment]
@djdupre done. Is that good enough?

**Comment by djdupre** [comment]
Yes thanks

**Comment by djdupre** [comment]
@christineta Can you document the authentication service in the docs branch today?
