### ISSUE TITLE
Fix GitHub pages Firebase OAuth

### ISSUE THREAD

**Issue by djdupre** [cse403trackforever/webapp#75]
Signing in at https://cse403trackforever.github.io/webapp/signin with GitHub currently gives the following error:

> Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. Add your domain (cse403trackforever.github.io) to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**Comment by christineta** [comment]
@djdupre I didn't register the domain into Firebase. Can you check if it works for you now?

**Comment by djdupre** [comment]
Yes it's working now
