### ISSUE TITLE
Handle GitHub API rate limits

### ISSUE THREAD

**Issue by djdupre** [cse403trackforever/webapp#82]
We often get this response when making an API call to GItHub:
```JSON
{
  "message": "API rate limit exceeded for 205.175.107.48. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
This is a big problem for even small projects (limit is 60 for unauthorized users).

**Comment by christineta** [comment]
We will have each user generate a personal access token that will increase each user's rate limit to 5000 requests / hour. 
- Store token to their Firebase database
- For every GitHub request, add access_token=TOKEN to query parameters
- Stretch: have user-friendly messages for when we don't have the token, rate limit has been reached, etc.

**Comment by christineta** [comment]
Also #190
