### ISSUE TITLE
Issue viewing page does not resize inline images from GitHub

### ISSUE THREAD

**Issue by jaredtle** [cse403trackforever/webapp#83]
Example issue that contains inline image:
[Here](https://github.com/MinecraftForge/MinecraftForge/issues/4917)

Result of attempting to view issue after import (zoomed out to show effect):
[capture](https://user-images.githubusercontent.com/29386164/39904131-4acd2e54-548b-11e8-8c32-038d4514ca23.png)

**Comment by christineta** [comment]
Attaching this for testing

![39795231-a81e6cbc-5346-11e8-941d-d13b10af9c54](https://user-images.githubusercontent.com/19314551/40800174-78b31100-64c4-11e8-8044-94a185233798.png)

**Comment by christineta** [comment]
What it looks like after fix
<img width="1440" alt="screen shot 2018-05-31 at 11 32 14 am" src="https://user-images.githubusercontent.com/19314551/40800831-47621fe0-64c6-11e8-8766-baf3210f9e24.png">

**Comment by christineta** [comment]
#199
